name: CI-Tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  playModeTests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: webbertakken/unity-test-runner@v1.6
        id: testStep
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
          #TEST_MODE: editmode
        with:
          unityVersion: 2019.4.8f1
      
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: Test results
          path: ${{ steps.testStep.outputs.artifactsPath }}
